#!/usr/bin/env python3
"""Calculator 1 module with basic arithmetic functions."""


def add(a, b):
    """Return the sum of a and b."""
    return a + b


def sub(a, b):
    """Return the difference of a and b."""
    return a - b


def mul(a, b):
    """Return the product of a and b."""
    return a * b


def div(a, b):
    """Return the integer division of a and b."""
    return int(a / b)
